variables:
  - ${{ if eq(variables['build.sourceBranch'], 'refs/heads/main') }}:
    - name: awsProviderVersion
      value: '5.31'          # Default 4.59 ( values: 4.59 and 5.31 )
    - name: account_id
      value: '634614730521'  # Sanbox ID AWS Account Sample
    - name: tfVersion
      value: '1.6.6'         # Default 1.4.4 ( values: 1.4.4 and 1.6.6 )
    - name: environment
      value: 'pdn'
  - ${{ if eq(variables['build.sourceBranch'], 'refs/heads/release') }}:
    - name: awsProviderVersion
      value: '5.31'          # Default 4.59 ( values: 4.59 and 5.31 )
    - name: account_id
      value: '634614730521'  # Sanbox ID AWS Account Sample
    - name: tfVersion
      value: '1.6.6'         # Default 1.4.4 ( values: 1.4.4 and 1.6.6 )
    - name: environment
      value: 'qa'
  - ${{ if eq(variables['build.sourceBranch'], 'refs/heads/develop') }}:
    - name: awsProviderVersion
      value: '5.31'          # Default 4.59 ( values: 4.59 and 5.31 )
    - name: account_id
      value: '634614730521'  # Sanbox ID AWS Account Sample
    - name: tfVersion
      value: '1.6.6'         # Default 1.4.4 ( values: 1.4.4 and 1.6.6 )
    - name: environment
      value: 'dev'
  - ${{ if eq(variables['build.sourceBranch'], 'refs/heads/feat/2024/sp14/hu-5419399') }}:
    - name: awsProviderVersion
      value: '5.31'          # Default 4.59 ( values: 4.59 and 5.31 )
    - name: account_id
      value: '634614730521'  # Sanbox ID AWS Account Sample
    - name: tfVersion
      value: '1.6.6'         # Default 1.4.4 ( values: 1.4.4 and 1.6.6 )
    - name: environment
      value: 'dev'