variables:
  - ${{ if eq(variables['build.sourceBranch'], 'refs/heads/main') }}:
    - name: awsProviderVersion
      value: '4.59'          # values: 4.59 and 5.31
    - name: account_id
      value: '111111111111'  # ID of AWS account PDN
    - name: tfVersion
      value: '1.4.4'         # values: 1.4.4 and 1.6.6
  - ${{ if eq(variables['build.sourceBranch'], 'refs/heads/release') }}:
    - name: awsProviderVersion
      value: '4.59'          # values: 4.59 and 5.31
    - name: account_id
      value: '111111111111'  # ID of AWS account QA
    - name: tfVersion
      value: '1.4.4'         # values: 1.4.4 and 1.6.6
  - ${{ if eq(variables['build.sourceBranch'], 'refs/heads/develop') }}:
    - name: awsProviderVersion
      value: '4.59'          # values: 4.59 and 5.31
    - name: account_id
      value: '111111111111'  # ID of AWS account DEV
    - name: tfVersion
      value: '1.4.4'         # values: 1.4.4 and 1.6.6
  - ${{ if eq(variables['build.sourceBranch'], 'refs/heads/stg') }}:
    - name: awsProviderVersion
      value: '4.59'          # values: 4.59 and 5.31
    - name: account_id
      value: '111111111111'  # ID of AWS account STG
    - name: tfVersion
      value: '1.4.4'         # values: 1.4.4 and 1.6.6
  - ${{ if eq(variables['build.sourceBranch'], 'refs/heads/sbx') }}:
    - name: awsProviderVersion
      value: '4.59'          # values: 4.59 and 5.31
    - name: account_id
      value: '111111111111'  # ID of AWS account SBX
    - name: tfVersion
      value: '1.4.4'         # values: 1.4.4 and 1.6.6
